openapi: 3.0.0

info:
  title: GLIMPS Malware - Detect
  description: This API allows user to submit binary files to be analyzed
  version: '2.6.0'

paths:
  /submit:
    post:
      summary: Submit a file to be analyzed
      description: ''
      operationId: ''
      security:
        - ApiAuthKey: []
      parameters:
        - name: bypass-cache
          in: query
          required: false
          schema:
            type: boolean
          example: false
          description: ask API to bypass cache and always submit file to orchestrator (optional)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                tags:
                  type: string
                  description: user tags, each tag separated by a ','
                archive_password:
                  type: string
                  description: password used to extract archive
                bypass-cache:
                  type: boolean
                  description: ask API to bypass cache and always submit file to orchestrator
                description:
                  type: string
                  description: custom description for analysis
              required:
                - file
      responses:
        200:
          description: file submitted
          content:
            application/json:
              schema:
                type: object
                required:
                  - "status"
                properties:
                  status:
                    $ref: "#/components/schemas/submitStatus"
                  uuid:
                    $ref: "#/components/schemas/uuid"
                  error:
                    $ref: "#/components/schemas/error"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        429:
          description: user reach her quota
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                quota-exceeded:
                  description: user exceeded her daily quota (number of submission in 24h)
                  value:
                    status: false
                    error: "quota exceeded, try again in 24h"
        500:
          $ref: '#/components/responses/InternalServerError'
  /results:
    get:
      summary: Returns results by date (from -> to) in seconds
      security:
        - ApiAuthKey: []
      parameters:
        - name: from
          in: query
          schema: 
            type: integer
            minimum: 0
            default: 86400
            example: 86400
          description: |
            Results *from* now minus this value in seconds will be returned

            Here 86400 seconds for one day
        - name: to
          in: query
          schema: 
            type: integer
            minimum: 0
            default: 0
            example: 86400
          description: |
            Results *until* now minus this value in seconds will be returned
            
            Here 86400 seconds for one day
        - name: size
          in: query
          schema:
            type: integer
            minimum: 0
            default: 10
            example: 15
          description: Number of results to be returned
        - name: offset
          in: query
          schema:
            minimum: 0
            type: integer
            default: 0
            example: 10
          description: Offset to be applied to the returned results index
        - name: tags
          in: query
          schema:
            type: array
            example: "test"
          description: filter on user tags
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/resultsByDate"
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /results/{UUID}:
    get:
      summary: Retrieve the analysis
      description: ''
      operationId: ''
      security:
        - ApiAuthKey: []
      parameters:
        - name: UUID
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/uuid"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/analysis"
              examples:
                analysisCompletedMinimal:
                  $ref: "#/components/examples/analysisCompletedMinimal"
                analysisInProgress:
                  $ref: "#/components/examples/analysisInProgress"
                analysisWithSubFiles:
                  $ref: "#/components/examples/analysisWithSubFiles"
                analysisWithSubFilesMalware:
                  $ref: "#/components/examples/analysisWithSubFilesMalware"
                analysisWithToken:
                  $ref: "#/components/examples/analysisWithToken"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /results/{UUID}/full:
    get:
      summary: Retrieve full analysis
      description: ''
      operationId: ''
      security:
        - ApiAuthKey: []
      parameters:
        - name: UUID
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/uuid"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/fullAnalysis"
              examples:
                analysisCompleted:
                  $ref: "#/components/examples/fullAnalysisMalware"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /search/{sha256}:
    get:
      summary: Search a previous analysis
      description: ''
      operationId: ''
      security:
        - ApiAuthKey: []
      parameters:
        - name: sha256
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/sha256"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/analysis"
              examples:
                analysisCompletedMinimal:
                  $ref: "#/components/examples/analysisCompletedMinimal"
                analysisInProgress:
                  $ref: "#/components/examples/analysisInProgress"
                analysisWithSubFiles:
                  $ref: "#/components/examples/analysisWithSubFiles"
                analysisWithSubFilesMalware:
                  $ref: "#/components/examples/analysisWithSubFilesMalware"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /results/{UUID}/{SHA256}/service/{SERVICE}:
    get:
      summary: get JSON body result for a given service and an analysis file
      description: get JSON body result
      security:
        - ApiAuthKey: []
      parameters:
        - name: UUID
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/uuid"
        - name: SHA256
          in: path
          required: true
          schema:
            $ref:  "#/components/schemas/sha256"
        - name: SERVICE
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/service"
      responses:
        200:
          description: service result
          content:
            application/json:
              schema:
               type: object 
              examples:
                SignatureUmbrella:
                  value:
                    av_name: "signature_umbrella"
                    av_version: "8.3.64.72"
                    db_version: "8.19.2.26"
                    malware: true
                    malware_name: "TR/Crypt.XPACK.Gen"
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /status:
    get:
      operationId: getProfileStatus
      summary: Get profile status.
      description: Get profile status. The status will contains quota state and an estimation of analysis duration.
      security:
        - ApiAuthKey: []
      responses:
        200:
          description: profile status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profileStatus"
              examples:
                static:
                  $ref: "#/components/examples/staticProfileStatus"
                dynamic:
                  $ref: "#/components/examples/dynamicProfileStatus"
components:
  responses:
    BadRequest:
      description: invalid file submitted
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/badRequest"
          examples:
            'anonymous archive':
              description: anonymous user try to submit archive file
              value:
                status: false
                error: invalid filetype
                details: [{"file": "invalid filetype"}]
            'invalid file size':
              description: submitted file size is bigger than limit
              value:
                status: false
                error: bad request
                details: [{"file": "invalid file size (0<size<95.4 mib)"}]
            'file is required':
              description: file is required
              value:
                status: false
                error: bad request
                details: [{"file": "file is required"}]
            'invalid request parameter':
              description: user used an invalid request parameter
              value:
                status: false
                error: "bad request"
                details: [{"key": "error description"}]
            'bad request':
              value:
                status: false
                error: "bad request"
    Forbidden:
      description: user try to submit a file without submit permission
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
          examples:
            bypass-cache:
              description: user without bypass cache permission tried to bypass cache
              value:
                status: false
                error: "bypass-cache denied"
            submit:
              description: user without submit permission tried to submit a file
              value:
                status: false
                error: "submit denied"
            search:
              description: user without search permission tried to search a result
              value:
                status: false
                error: "search denied"
            forbidden:
              description: user without search permission try to request search
              value:
                status: false
                error: "forbidden"
    NotFound:
      description: user try to access resources that does not exist
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
          examples:
            notfound:
              value:
                status: false
                error: "not found"
    InternalServerError:
      description: unexpected error from server
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
          examples:
            internalservererror:
              value:
                status: false
                error: "internal server error"
    Unauthorized:
      description: invalid token
      content:
        application/json:
          schema:
             $ref: "#/components/schemas/errorResponse"
          examples:
            unauthorized:
              value:
                status: false
                error: "unauthorized"
  securitySchemes:
    ApiAuthKey:
      type: apiKey
      in: header
      name: X-Auth-Token
      description: |
        Authentication token for the lite api
  schemas:
    authToken:
      type: string
      description: |
        Authentication token for the lite api
      example: "3559a8d2-c497f9f3-0c4fb9f2-79d627d2-6f0847c5"
    submitStatus:
      type: boolean
      description: |
        true => analysis in progress,
        false => an error occurred
    badRequest:
      type: object
      properties:
        status:
          default: false
          type: boolean
          description: false => an error occurred
        error:
          type: string
          description: string describing error 
        details:
          type: array
          description: human readable message for each key in error
          items:
            type: object
    errorResponse:
      type: object
      required:
        - "status"
      properties:
        status:
          default: false
          type: boolean
          description: false => an error occurred
        error:
          type: string
          description: string describing error
    resultsByDate:
      type: object
      properties:
        count: 
          type: integer
          example: 1
        submissions:
          type: array
          items:
            type: object
            properties:
              uuid:
                $ref: "#/components/schemas/uuid"
              is_malware:
                $ref: "#/components/schemas/is_malware"
              done:
                $ref: "#/components/schemas/done"
              error:
                $ref: "#/components/schemas/error"
              filename:
                $ref: "#/components/schemas/filename"
              date:
                $ref: "#/components/schemas/timestamp"
              file_size:
                $ref: "#/components/schemas/size"
              file_type:
                $ref: "#/components/schemas/filetype"
              score:
                $ref: "#/components/schemas/score"
              malwares:
                $ref: "#/components/schemas/malwares"
              special_status_code:
                $ref: "#/components/schemas/special_status_code"
            example: 
              - uuid: "6ed43200-4789-4ab5-ad19-064469c129dd"
                is_malware: true
                done: true
                error: false
                filename: "test.bin"
                date: 1675850874780
                file_size: 12340
                file_type: "zip"
                score: 1200
                malwares: ["eicar"]
                special_status_code: 103
              - uuid: "6ed43200-4789-4ab5-ad19-064469c129ee"
                is_malware: false
                done: false
                error: false
                filename: "test.exe"
                date: 1675850071234
                file_size: 1234
                file_type: "exe"
                score: 0
                malwares: []
                special_status_code: 0
    analysis:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/status"
        uuid:
          $ref: "#/components/schemas/uuid"
        sid:
          $ref: "#/components/schemas/sid"
        sha256:
          $ref: "#/components/schemas/sha256"
        sha1:
          $ref: "#/components/schemas/sha1"
        md5:
          $ref: "#/components/schemas/md5"
        ssdeep:
          $ref: "#/components/schemas/ssdeep"
        is_malware:
          $ref: "#/components/schemas/is_malware"
        score:
          $ref: "#/components/schemas/score"
        done:
          $ref: "#/components/schemas/done"
        timestamp:
          $ref: "#/components/schemas/timestamp"
        duration:
          $ref: "#/components/schemas/duration"
        error:
          $ref: "#/components/schemas/error"
        errors:
          $ref: "#/components/schemas/errors"
        filetype:
          $ref: "#/components/schemas/filetype"
        size:
          $ref: "#/components/schemas/size"
        filenames:
          $ref: "#/components/schemas/filenames"
        files:
          $ref: "#/components/schemas/files"
        file_count:
          $ref: "#/components/schemas/file_count"
        token:
          $ref: "#/components/schemas/view_token"
        malwares:
          $ref: "#/components/schemas/malwares"
        threats:
          $ref: "#/components/schemas/threats"
        special_status_code:
          $ref: "#/components/schemas/special_status_code"
      required:
        - status
        - UUID
        - sid
        - sha256
        - sha1
        - md5
        - ssdeep
        - is_malware
        - score
        - done
        - timestamp
        - duration
        - filetype
        - filecount
        - special_status_code
    fullAnalysis:
      type: object
      properties:
        archive_ts:
          $ref: "#/components/schemas/archive_ts"
        classification:
          $ref: "#/components/schemas/classification"
        error_count:
          $ref: "#/components/schemas/error_count"
        errors:
          $ref: "#/components/schemas/errors"
        expiry_ts:
          $ref: "#/components/schemas/expiry_ts"
        file_count:
          $ref: "#/components/schemas/file_count"
        file_infos:
          $ref: "#/components/schemas/file_infos"
        file_tree:
          $ref: "#/components/schemas/file_tree"
        files:
          $ref: "#/components/schemas/files"
        max_score:
          $ref: "#/components/schemas/max_score"
        metadata:
          $ref: "#/components/schemas/metadata"
        missing_error_keys:
          $ref: "#/components/schemas/missing_error_keys"
        missing_result_keys:
          $ref: "#/components/schemas/missing_result_keys"
        params:
          $ref: "#/components/schemas/params"
        results:
          $ref: "#/components/schemas/results"
        sid:
          $ref: "#/components/schemas/sid"
        state:
          $ref: "#/components/schemas/state"
        times:
          $ref: "#/components/schemas/times"
        verdict:
          $ref: "#/components/schemas/verdict"
        special_status_code:
          $ref: "#/components/schemas/special_status_code"
      required:
        - archive_ts
        - classification
        - error_count
        - expiry_ts
        - file_count
        - file_infos
        - file_tree
        - files
        - max_score
        - metadata
        - missing_error_keys
        - missing_result_keys
        - params
        - results
        - sid
        - state
        - times
        - verdict
        - special_status_code
    archive_ts:
      type: string
      example: "2024-04-19T11:54:46.398882Z"
    classification:
      type: string
    error_count:
      type: integer
    expiry_ts:
      type: string
    file_infos:
      description: file information
      type: object
    file_tree:
      type: object
    max_score:
      type: integer
    metadata:
      type: object
    missing_error_keys:
      type: array
    missing_result_keys:
      type: array
    params:
      type: object
    results:
      type: object
    state:
      type: string
    times:
      type: object
    verdict:
      type: object
    status:
      type: boolean
      description: |
        true => no error to report,
        false => an error occurred
    sid:
      description: |
        analysis UUID handled by GLIMPS malware finder - expert
        could be used to construct expert link like:
        https://gmalware.useddomain.glimps.re/expert/en/analysis/results/advanced/${SID}
      type: string
      example: 2z4zfg66Sm3k0Y2KcjgqoK
    uuid:
      type: string
      description: |
        Unique analysis identifier
      example: "9618ae7e-e284-405d-8998-ff1e12c7ca27"
    sha256:
      type: string
      description: string hex encoded input file SHA256
      example: "c253396cf740b03629b1a76f071eb3594099eebc130f47ae8fe15ef47679e209"
    sha1:
      type: string
      description: string hex encoded input file SHA1
      example: "f9a0a612aa694acc24726ed8610981db9798dde0"
    md5:
      type: string
      description: string hex encoded input file MD5
      example: "8437115b99341df5becdb03a4d091654"
    ssdeep:
      type: string
      description: string input file SSDeep
      example: "384:4fpWcehzJFYKWYGWhdffa3zWzc3fpCLrsjHIX69URc+hmnulY1qHprFKt6zW8zZn:4fkcY/WYf/ffa3axfpWcehzJFYKWYGWv"
    is_malware:
      type: boolean
      description: analysis result, is a malware or not
    score:
      type: integer
      description: highest score given by probes
      example: 1000
    done:
      type: boolean
      description: is the analysis finished
    timestamp:
      type: integer
      description: |
        timestamp of the start of analysis in milliseconds
        timestamp is 0 for anonymous user
    duration:
      type: integer
      description: duration of the analysis in milliseconds
      example: 998
    error:
      type: string
      description: error message if Status is false
    errors:
      type: object
      description: error message by services
      additionalProperties:
        type: string
    filetype:
      type: string
      description: ''
    size:
      type: integer
      description: input file size (in bytes)
    magic:
      type: string
      description: file magic - file type
    file_count:
      description: amount of file in the submission (input + extracted)
      type: integer
      example: 1
    filename:
      type: string
      description: name of the input file
    filenames:
      type: array
      description: list of analyzed filename
      items:
        type: string
    files:
      description: array of submission files (input file and extracted sub-files)
      type: array
      items:
        $ref: "#/components/schemas/fileEntry"
    fileEntry:
      description: file information
      type: object
      properties:
        sha256:
          $ref: "#/components/schemas/sha256"
        sha1:
          $ref: "#/components/schemas/sha1"
        md5:
          $ref: "#/components/schemas/md5"
        ssdeep:
          $ref: "#/components/schemas/ssdeep"
        magic:
          $ref: "#/components/schemas/magic"
        av_results:
          $ref: "#/components/schemas/av_results"
        size:
          $ref: "#/components/schemas/size"
        is_malware:
          $ref: "#/components/schemas/is_malware"
    av_results:
      description: malware matches returns by probes, print av_result right required
      type: object
      properties:
        av:
          type: string
          description: probe name
          example: "GlimpsCorrelate"
        result:
          type: string
          description: malware name indicated by probe
          example: win_cybergate_auto
        score:
          type: integer
          description: amount of point added by the probe
          example: 1000
    view_token:
      description: token that can be used to view analysis result in expert view
      type: string
    malwares:
      type: array
      description: list of malware names found in analysis
      items:
        type: string
    service:
      type: string
      description: service name
      example: GlimpsCorrelate
    threats:
      description: |
        Summary of threats found in submission.
        Each submission file reaching threshold score will add an entry.
        Entry keys are the SHA256 of files
      type: object
      additionalProperties:
        type: object
        properties:
          filenames:
            $ref: "#/components/schemas/filenames"
          tags:
            description: list of tag of interest
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  description: tag name
                value:
                  type: string
                  description: tag value
          score:
            $ref: "#/components/schemas/score"
          magic:
            $ref: "#/components/schemas/magic"
          sha256:
            $ref: "#/components/schemas/sha256"
          sha1:
            $ref: "#/components/schemas/sha1"
          md5:
            $ref: "#/components/schemas/md5"
          ssdeep:
            $ref: "#/components/schemas/ssdeep"
          file_size:
            $ref: "#/components/schemas/size"
          mime:
            $ref: "#/components/schemas/mime"
    mime:
      type: string
      description: file mime type
      example: text/plain
    special_status_code:
      type: integer
      description: "Code identifying a special case among:\n
        - case 1 -> archive extraction failed\n
          \t- sub-case 1 -> archive password unknown, code=101\n
          \t- sub-case 2 -> too many files in archive or file too big, code=102\n
        - case 2 -> no signatures in result, code=103\n
        - case 3 -> negative score (whitelisted file), code=104\n\n
        If no special case, **code=0**.\n\n
        If multiple cases match, the code is given following the priority order: 104, 101, 102, 103
      "
      example: 103
    profileStatus:
      type: object
      description: status of a profile
      properties:
        daily_quota:
          $ref: "../../../shared/schemas.yml#/components/schemas/daily_quota"
        available_daily_quota:
          type: integer
          description: |
            number of submission still available.
            0 => unlimited
            available_daily_quota is computed on the last 24h, so it could increase and decrease anytime.
        cache:
          type: boolean
          description: true if detect (SHA256 based) cache is activated for the profile.
        estimated_analysis_duration:
          type: integer
          description: |
            An estimation of the duration used by the next analysis in milliseconds.
            It's an optimistic estimation, taking into account the average duration of each service and the state of the orchestrator.
  examples:
    analysisCompletedMinimal:
      value: |
        {
          "status": true,
          "uuid": "9618ae7e-e284-405d-8998-ff1e12c7ca27",
          "sha256": "c253396cf740b03629b1a76f071eb3594099eebc130f47ae8fe15ef47679e209",
          "sha1": "f9a0a612aa694acc24726ed8610981db9798dde0",
          "md5": "8437115b99341df5becdb03a4d091654",
          "ssdeep": "384:4fpWcehzJFYKWYGWhdffa3zWzc3fpCLrsjHIX69URc+hmnulY1qHprFKt6zW8zZn:4fkcY/WYf/ffa3axfpWcehzJFYKWYGWv",
          "is_malware": true,
          "done": true,
          "timestamp": 1637835534067,
          "filetype": "elf",
          "size": 31976,
          "special_status_code": 103
        }
    analysisInProgress:
      value: |
        {
          "status":true,
          "uuid":"9e0c5344-b902-4675-b257-2fe9ce088774",
          "sha256":"024e01b39ec72691f43f9b480656dde0ada5b5d03fc0f000fd06ccdc5eda627e",
          "sha1":"",
          "md5":"",
          "ssdeep":"",
          "is_malware":false,
          "score":0,
          "done":false,
          "timestamp":1622549930559,
          "filetype":"exe",
          "size":69632,
          "file_count":0,
          "duration":0
        }
    analysisWithSubFiles:
      value: |
        {
          "status":true,
          "uuid":"e6520192-bc2a-4172-b68f-cc2de1664807",
          "sha256":"edae201c466883b46294e5216c8d364420c13282abefcfcdea28d59ec0b671b0",
          "sha1":"130d5c720227ca89695d454397b66c3a402aac49",
          "md5":"309ef08aa4d778a08151ca3532b8e424",
          "ssdeep":"24576:645Rt4El7fc/TFJzjJUgrrCq5sNIwQsUGy1q7a9DlI5CTp+kq9slRG:Rjt4El7fc/TFJWstwQsPdSDu5CTpqmG",
          "is_malware":false,
          "score":0,
          "done":true,
          "timestamp":1622449879758,
          "filetype":"exe",
          "size":1294336,
          "filenames":["test.bin"],
          "files":[
            {
              "sha256":"edae201c466883b46294e5216c8d364420c13282abefcfcdea28d59ec0b671b0",
              "sha1":"130d5c720227ca89695d454397b66c3a402aac49",
              "md5":"309ef08aa4d778a08151ca3532b8e424",
              "ssdeep":"24576:645Rt4El7fc/TFJzjJUgrrCq5sNIwQsUGy1q7a9DlI5CTp+kq9slRG:Rjt4El7fc/TFJWstwQsPdSDu5CTpqmG",
              "magic":"PE32 executable (GUI) Intel 80386, for MS Windows",
              "size":1294336,
              "is_malware":false
            }
          ],
          "sid":"1HLXVrb5dMFrXpgSTGnScd",
          "file_count":1,
          "duration":6206,
          "special_status_code": 103
        }
    analysisWithSubFilesMalware:
      value: |
        {
          "status":true,
          "uuid":"1a6624c6-d2e1-4308-87a0-43856f3103a4",
          "sha256":"2213f9c41331201f97ee0be46031c5aacb7eea2b2cc4d9a074247390e2d14787",
          "sha1":"00404dcffa713b573ba7435c5e73302b3e702e4e",
          "md5":"4cc0ee72e4fc5c2e90fc078ce445e7ec",
          "ssdeep":"768:TC38CMQ2Is0JQj+zRdZHJE5s6jtBnDshPJSudb5T:TChMSJHRdZHJqtBy3db",
          "is_malware":true,
          "score":2000,
          "done":true,
          "timestamp":1622194918662,
          "filetype":"exe",
          "size":39424,
          "filenames":["UDS.DangerousObject.Multi.Generic.4cc0ee72e4fc5c2e90fc078ce445e7ec"],
          "malwares":[
            "Trojan.Downloader.cGW@a8pVnZm.32729.13424",
            "win_cybergate_auto","win_cybergate_w0"
          ],
          "files":[
          {
            "sha256":"2213f9c41331201f97ee0be46031c5aacb7eea2b2cc4d9a074247390e2d14787",
            "sha1":"00404dcffa713b573ba7435c5e73302b3e702e4e",
            "md5":"4cc0ee72e4fc5c2e90fc078ce445e7ec",
            "ssdeep":"768:TC38CMQ2Is0JQj+zRdZHJE5s6jtBnDshPJSudb5T:TChMSJHRdZHJqtBy3db",
            "magic":"PE32 executable (GUI) Intel 80386, for MS Windows",
            "av_results":[
              {
                "av":"Clamav",
                "result":"Trojan.Downloader.cGW@a8pVnZm.32729.13424",
                "score":1000
              },
              {
                "av":"GlimpsCorrelate",
                "result":"win_cybergate_auto",
                "score":1000
              },
              {
                "av":"GlimpsCorrelate",
                "result":"win_cybergate_w0",
                "score":1000
              }],
            "size":39424,
            "is_malware":true
          }],
          "sid":"2z4zfg66Sm3k0Y2KcjgqoK",
          "file_count":1,
          "duration":988,
          "threats":{
            "2213f9c41331201f97ee0be46031c5aacb7eea2b2cc4d9a074247390e2d14787": {
              "filenames": ["UDS.DangerousObject.Multi.Generic.4cc0ee72e4fc5c2e90fc078ce445e7ec"],
              "tags": [
                {"name": "av.virus_name", "value":"Trojan.Downloader.cGW@a8pVnZm.32729.13424"},
                {"name": "av.virus_name", "value":"win_cybergate_auto"},
                {"name": "av.virus_name", "value":"win_cybergate_w0"}
              ],
              "score": 2000,
              "magic": "PE32 executable (GUI) Intel 80386, for MS Windows",
              "sha256":"2213f9c41331201f97ee0be46031c5aacb7eea2b2cc4d9a074247390e2d14787",
              "sha1":"00404dcffa713b573ba7435c5e73302b3e702e4e",
              "md5":"4cc0ee72e4fc5c2e90fc078ce445e7ec",
              "ssdeep":"768:TC38CMQ2Is0JQj+zRdZHJE5s6jtBnDshPJSudb5T:TChMSJHRdZHJqtBy3db",
              "file_size": 39424,
              "mime": "executable/windows"
            }
          },
          "special_status_code": 103
        }
    analysisWithToken:
      value: |
        {
          "status":true,
          "uuid":"1a6624c6-d2e1-4308-87a0-43856f3103a4",
          "sha256":"2213f9c41331201f97ee0be46031c5aacb7eea2b2cc4d9a074247390e2d14787",
          "sha1":"00404dcffa713b573ba7435c5e73302b3e702e4e",
          "md5":"4cc0ee72e4fc5c2e90fc078ce445e7ec",
          "ssdeep":"768:TC38CMQ2Is0JQj+zRdZHJE5s6jtBnDshPJSudb5T:TChMSJHRdZHJqtBy3db",
          "is_malware":true,
          "score":2000,
          "done":true,
          "timestamp":1622194918662,
          "filetype":"exe",
          "size":39424,
          "filenames":["UDS.DangerousObject.Multi.Generic.4cc0ee72e4fc5c2e90fc078ce445e7ec"],
          "malwares":[
            "Trojan.Downloader.cGW@a8pVnZm.32729.13424",
            "win_cybergate_auto","win_cybergate_w0"
          ],
          "files":[
          {
            "sha256":"2213f9c41331201f97ee0be46031c5aacb7eea2b2cc4d9a074247390e2d14787",
            "sha1":"00404dcffa713b573ba7435c5e73302b3e702e4e",
            "md5":"4cc0ee72e4fc5c2e90fc078ce445e7ec",
            "ssdeep":"768:TC38CMQ2Is0JQj+zRdZHJE5s6jtBnDshPJSudb5T:TChMSJHRdZHJqtBy3db",
            "magic":"PE32 executable (GUI) Intel 80386, for MS Windows",
            "av_results":[
              {
                "av":"Clamav",
                "result":"Trojan.Downloader.cGW@a8pVnZm.32729.13424",
                "score":1000
              },
              {
                "av":"GlimpsCorrelate",
                "result":"win_cybergate_auto",
                "score":1000
              },
              {
                "av":"GlimpsCorrelate",
                "result":"win_cybergate_w0",
                "score":1000
              }],
            "size":39424,
            "is_malware":true
          }],
          "sid":"2z4zfg66Sm3k0Y2KcjgqoK",
          "file_count":1,
          "duration":988,
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFwaS10ZXN0dG9rZW4iLCJncm91cHMiOlsidG9rZW5zIl0sInNpZCI6IjdSaWtpYXFZdVNpOUU1cmV3NHFBY2UiLCJleHAiOjE2NDA1MTE2MDgsImlhdCI6MTYzNzkxOTYwOH0.AWa_e8EazpXq-7NHARE1xYGaRrHkF-IGRjw2yE6V8HY",
          "threats":{
            "2213f9c41331201f97ee0be46031c5aacb7eea2b2cc4d9a074247390e2d14787": {
              "filenames": ["UDS.DangerousObject.Multi.Generic.4cc0ee72e4fc5c2e90fc078ce445e7ec"],
              "tags": [
                {"name": "av.virus_name", "value":"Trojan.Downloader.cGW@a8pVnZm.32729.13424"},
                {"name": "av.virus_name", "value":"win_cybergate_auto"},
                {"name": "av.virus_name", "value":"win_cybergate_w0"}
              ],
              "score": 2000,
              "magic": "PE32 executable (GUI) Intel 80386, for MS Windows",
              "sha256":"2213f9c41331201f97ee0be46031c5aacb7eea2b2cc4d9a074247390e2d14787",
              "sha1":"00404dcffa713b573ba7435c5e73302b3e702e4e",
              "md5":"4cc0ee72e4fc5c2e90fc078ce445e7ec",
              "ssdeep":"768:TC38CMQ2Is0JQj+zRdZHJE5s6jtBnDshPJSudb5T:TChMSJHRdZHJqtBy3db",
              "file_size": 39424,
              "mime": "executable/windows"
            }
          },
          "special_status_code": 103
        }
    staticProfileStatus:
      value: |
        {
          "daily_quota": 100000,
          "available_daily_quota": 100000,
          "cache": true,
          "estimated_analysis_duration": 2080
        }
    dynamicProfileStatus:
      value: |
        {
          "daily_quota": 1000,
          "available_daily_quota": 950,
          "cache": false,
          "estimated_analysis_duration": 208000
        }
    fullAnalysisMalware:
      value: |
        {
          "archive_ts": "2024-04-19T13:13:59.966447Z",
          "classification": "TLP:W",
          "error_count": 0,
          "expiry_ts": "2024-05-04T13:13:59.966459Z",
          "file_count": 2,
          "file_infos": {
            "223e7167a4e3613ea5ea5465f96fb149d301ef44115d9795c48857cb958eccb8": {
              "archive_ts": "2026-04-15T09:11:44.76619Z",
              "ascii": "PK..3...c..I{X....M.......D...2a82243697e2eec45bedc754adcdc1f6f4",
              "classification": "TLP:W",
              "entropy": 7.9985514,
              "expiry_ts": "2026-04-30T09:11:44.766093Z",
              "hex": "",
              "magic": "Zip archive data, at least v5.1 to extract",
              "md5": "640530dcf41bdb8cff2173b09b6e81da",
              "mime": "application/zip",
              "seen": {
                "count": 17,
                "first": "2024-03-27T09:09:53.474105Z",
                "last": "2024-04-04T13:14:00.014399Z"
              },
              "sha1": "88fcec4db80c9900910cc1eda1687c41bc597c37",
              "sha256": "223e7167a4e3613ea5ea5465f96fb149d301ef44115d9795c48857cb958eccb8",
              "size": 117325,
              "ssdeep": "3072:8dv8E1+hqsMBWK51qrIewq17JlAmgWmlTbQCWRpNVL:mvN+hqsgv5IrHwaJlAmo8CWRpXL",
              "type": "archive/zip"
            },
            "2a82243697e2eec45bedc754adcdc1f6f41724a40c6d7d96fd41ad144899b6f7": {
              "archive_ts": "2024-04-19T13:14:01.109003Z",
              "ascii": "MZ......................@.......................................",
              "classification": "TLP:W",
              "entropy": 5.068281,
              "expiry_ts": "2025-03-29T14:23:36.155443Z",
              "hex": "",
              "magic": "PE32 executable (GUI) Intel 80386 Mono/.Net assembly, for MS Windows, 3 sections",
              "md5": "832eb4dc3ed8ceb9a1735bd0c7acaf1b",
              "mime": "application/vnd.microsoft.portable-executable",
              "seen": {
                "count": 17,
                "first": "2024-03-27T09:09:54.957854Z",
                "last": "2024-04-04T13:14:01.146586Z"
              },
              "sha1": "b622a406927fbb8f6cd5081bd4455fb831948fca",
              "sha256": "2a82243697e2eec45bedc754adcdc1f6f41724a40c6d7d96fd41ad144899b6f7",
              "size": 308224,
              "ssdeep": "3::",
              "type": "executable/windows/pe32"
            }
          },
          "file_tree": {
            "223e7167a4e3613ea5ea5465f96fb149d301ef44115d9795c48857cb958eccb8": {
              "name": [
                "real_pain_332.zip"
              ],
              "score": 0,
              "sha256": "223e7167a4e3613ea5ea5465f96fb149d301ef44115d9795c48857cb958eccb8",
              "size": 117325,
              "truncated": false,
              "type": "archive/zip",
              "children": {
                "2a82243697e2eec45bedc754adcdc1f6f41724a40c6d7d96fd41ad144899b6f7": {
                  "name": [
                    "2a82243697e2eec45bedc754adcdc1f6f41724a40c6d7d96fd41ad144899b6f7.exe"
                  ],
                  "score": 0,
                  "sha256": "2a82243697e2eec45bedc754adcdc1f6f41724a40c6d7d96fd41ad144899b6f7",
                  "size": 308224,
                  "truncated": false,
                  "type": "executable/windows/pe32",
                  "children": {}
                }
              }
            }
          },
          "files": [
            {
              "name": "real_pain_332.zip",
              "sha256": "223e7167a4e3613ea5ea5465f96fb149d301ef44115d9795c48857cb958eccb8",
              "size": 117325
            }
          ],
          "max_score": 0,
          "metadata": {
            "user_groups__": ""
          },
          "missing_error_keys": [],
          "missing_result_keys": [],
          "params": {
            "classification": "TLP:W",
            "deep_scan": false,
            "description": "Inspection of file: real_pain_332.zip",
            "generate_alert": false,
            "groups": [],
            "services": {
              "excluded": [],
              "resubmit": [],
              "runtime_excluded": [],
              "selected": [
                "Extract"
              ]
            },
            "submitter": "",
            "ttl": 30,
            "type": ""
          },
          "results": {
            "Extract.v4_2_0": {
              "archive_ts": "2024-04-19T13:14:01.062411Z",
              "classification": "TLP:W",
              "created": "2024-04-04T13:14:01.175861Z",
              "drop_file": true,
              "expiry_ts": "2024-05-04T13:14:01.062446Z",
              "id": "",
              "response": {
                "extracted": [
                  {
                    "classification": "TLP:W",
                    "description": "Extracted using extract_zip",
                    "is_section_image": false,
                    "name": "2a82243697e2eec45bedc754adcdc1f6f41724a40c6d7d96fd41ad144899b6f7.exe",
                    "sha256": "2a82243697e2eec45bedc754adcdc1f6f41724a40c6d7d96fd41ad144899b6f7"
                  }
                ],
                "milestones": {
                  "service_completed": "2024-04-04T13:14:00.938255Z",
                  "service_started": "2024-04-04T13:14:00.646549Z"
                },
                "service_context": null,
                "service_debug_info": null,
                "service_name": "Extract",
                "service_tool_version": null,
                "service_version": "4.2.0.dev.fix-withsecure_zip_extraction",
                "supplementary": [
                  {
                    "classification": "TLP:W",
                    "description": "Result Ontology from Extract",
                    "is_section_image": false,
                    "name": "extract_223e7167a4e3613ea5ea5465f96fb149d301ef44115d9795c48857cb958eccb8.ontology",
                    "sha256": "a3c5768a1cb5bca18310bc24621927722a8422baaba979656cf843c058723855"
                  }
                ]
              },
              "result": {
                "score": 0,
                "sections": [
                  {
                    "body": [
                      {
                        "last_modified_date": "2024-03-27T09:08:22+00:00",
                        "name": "2a82243697e2eec45bedc754adcdc1f6f41724a40c6d7d96fd41ad144899b6f7.exe"
                      }
                    ],
                    "body_format": "JSON",
                    "classification": "TLP:W",
                    "depth": 0,
                    "heuristic": {
                      "attack": [],
                      "heur_id": "EXTRACT.10",
                      "name": "Extracted from Protected Archive",
                      "score": 0,
                      "signature": []
                    },
                    "tags": [
                      {
                        "short_type": "password",
                        "type": "info.password",
                        "value": "infected"
                      }
                    ],
                    "title_text": "Successfully extracted 1 file using password: infected"
                  }
                ]
              },
              "section_hierachy": null,
              "sha256": "223e7167a4e3613ea5ea5465f96fb149d301ef44115d9795c48857cb958eccb8"
            }
          },
          "sid": "1c15LZo0vU1GiRGDiy8OCC",
          "state": "completed",
          "times": {
            "completed": "2024-04-04T13:14:01.852268Z",
            "submitted": "2024-04-04T13:13:59.966457Z"
          },
          "verdict": {
            "malicious": [],
            "non_malicious": []
          },
          "special_status_code": 103
        }
servers:
  - url: https://{host}:{port}/{basePath}
    description: Test server
    variables:
      host:
        default: gmalware.glimps.lan
        description: Test server
      port:
        default: "443"
        enum:
          - "443"
      basePath:
        default: "api/lite/v2"
